spring.application.name=tactik-api
# 1. Conexión a la base de datos tactik_db que creaste antes
spring.datasource.url=jdbc:postgresql://localhost:5432/tactik_db
spring.datasource.username=postgres
spring.datasource.password=Elh0rmiguer031.

# 2. Le decimos a Spring qué motor de base de datos estamos usando
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3.Esto creará y actualizará tus tablas en PostgreSQL automáticamente
spring.jpa.hibernate.ddl-auto=update

# 4. Para ver por la consola de abajo el SQL
spring.jpa.show-sql=true
# 5. Configuracion de seguridad para la API
api.security.token.secret=cT2xR5v8Yp3s6V9yB4wE7zA1mD0fH2kL5jN8qU3oW6iX9gC4tP1rS0eM7aZ2bV5c